#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate the sample audio the I2S + ES8388 board test plays.

Without an input file a short melody is synthesised - the first two phrases of
"Twinkle, Twinkle, Little Star" (a public domain tune), as a music box: three
harmonics with a fast attack and an exponential decay. That is deliberate. A
single tone only tells whether *something* comes out; a melody tells whether the
bit clock and the frame clock are right, because a wrong divider shifts the
pitch and the tempo of every note, and a wrong word length or channel handling
turns it into noise.

With an input file the audio comes from that file instead, converted with ffmpeg
to what the sample expects (mono, 16 kHz, signed 16 bit little endian), so a
recording - music or speech - can be played through the board as well:

    west build -p always -b ls2k300_pai -d build/i2s_es8388 \
        samples/boards/loongson/ls2k300_pai/i2s_es8388 \
        -DEXTRA_CONF_FILE=build/pai_bringup_shell.conf \
        -DSAMPLE_AUDIO_INPUT=/path/to/audio.wav

Both outputs (sample_audio.c and sample_audio.h) are written into the build
directory given by --output-dir, so nothing generated is kept in the source
tree; the WAV itself is not needed at build time unless it is used as input.
"""

import argparse
import math
import os
import shutil
import struct
import subprocess
import sys
import wave

RATE = 16000      # clip rate; the sample interpolates it up to the link rate
NOTE_S = 0.32     # length of one quarter note
GAP_MS = 14       # articulation between the notes
VALUES_PER_LINE = 12

FREQ = {"C": 523.25, "D": 587.33, "E": 659.25, "F": 698.46, "G": 783.99, "A": 880.00}

# Twinkle, Twinkle, Little Star: C C G G A A G | F F E E D D C
MELODY = [("C", 1), ("C", 1), ("G", 1), ("G", 1), ("A", 1), ("A", 1), ("G", 2),
          ("F", 1), ("F", 1), ("E", 1), ("E", 1), ("D", 1), ("D", 1), ("C", 2)]

SOURCE_C = """\
/*
 * Generated by tools/make_sample_audio.py from %s.
 * Do not edit; the generator is the source of truth.
 */

#include <stddef.h>
#include <stdint.h>

const int16_t sample_audio_16k[] = {
%s
};

const size_t sample_audio_16k_samples =
\tsizeof(sample_audio_16k) / sizeof(sample_audio_16k[0]);
"""

SOURCE_H = """\
/*
 * Generated by tools/make_sample_audio.py - do not edit.
 */

#ifndef SAMPLE_AUDIO_H_
#define SAMPLE_AUDIO_H_

#include <stddef.h>
#include <stdint.h>

/* Mono, 16 bit, %u Hz; the sample interpolates it to the link rate */
extern const int16_t sample_audio_16k[];
extern const size_t sample_audio_16k_samples;

#endif /* SAMPLE_AUDIO_H_ */
""" % RATE


def synthesise():
    """The built in melody as 16 bit mono samples."""
    samples = []

    for name, beats in MELODY:
        freq = FREQ[name]
        length = NOTE_S * beats
        count = int(RATE * length)

        for i in range(count):
            t = i / RATE
            envelope = min(1.0, t / 0.008) * math.exp(-2.2 * t / length)
            wave = (math.sin(2 * math.pi * freq * t)
                    + 0.35 * math.sin(4 * math.pi * freq * t)
                    + 0.12 * math.sin(6 * math.pi * freq * t))
            value = (wave / 1.47) * envelope * 0.8
            samples.append(int(max(-1.0, min(1.0, value)) * 32767))

        samples.extend([0] * int(RATE * GAP_MS / 1000))

    return samples, "the built in melody"


def from_file(path):
    """A recording, either already in the clip format or through ffmpeg."""
    if path.lower().endswith(".wav"):
        try:
            with wave.open(path) as wav:
                if (wav.getnchannels() == 1 and wav.getframerate() == RATE
                        and wav.getsampwidth() == 2):
                    raw = wav.readframes(wav.getnframes())
                    return list(struct.unpack("<%dh" % (len(raw) // 2), raw)), path
        except wave.Error:
            pass

    if shutil.which("ffmpeg") is None:
        sys.exit("ffmpeg is needed for %s (or provide it as mono 16 kHz 16 bit WAV)"
                 % path)

    raw = subprocess.run(["ffmpeg", "-v", "error", "-i", path, "-ac", "1",
                          "-ar", str(RATE), "-f", "s16le", "-"],
                         check=True, stdout=subprocess.PIPE).stdout

    return list(struct.unpack("<%dh" % (len(raw) // 2), raw)), path


def write_c(samples, output_dir, source):
    lines = []
    for i in range(0, len(samples), VALUES_PER_LINE):
        lines.append("\t" + " ".join("%6d," % v for v in samples[i:i + VALUES_PER_LINE]))

    with open(os.path.join(output_dir, "sample_audio.c"), "w") as f:
        f.write(SOURCE_C % (source, "\n".join(lines)))

    with open(os.path.join(output_dir, "sample_audio.h"), "w") as f:
        f.write(SOURCE_H)


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--output-dir", required=True,
                        help="directory to write sample_audio.c/.h into")
    parser.add_argument("--input", default="",
                        help="WAV/recording to use instead of the built in melody")
    args = parser.parse_args()

    if args.input:
        samples, source = from_file(args.input)
    else:
        samples, source = synthesise()

    os.makedirs(args.output_dir, exist_ok=True)
    write_c(samples, args.output_dir, source)

    print("sample audio: %u samples, %.1f ms at %u Hz (%s)"
          % (len(samples), len(samples) * 1000.0 / RATE, RATE, source))


if __name__ == "__main__":
    main()
